### ISSUE TITLE
Plugin not showing up

### ISSUE THREAD

**Issue by Delmouly** [teran/deduplicator#2]
### What you've done step-by-step
Installed plugin via download, plugin manager.
Put in custom folder, with other (working) plugins  path is C:\Users\Photo\Pictures\catalogue lightroom\Plugins externes

### What you've expected to get as a result
Plugin working

### What you've got in fact
Plugin absent. I do see it in the plugin manager, installed and running, green dot. Help/Plugin extras is OK for checking updates for deduplicator.
But File/Plugin Extras shows only my other plugin (MIDI2LR)

[Deduplicator.log](https://github.com/teran/deduplicator/files/3588063/Deduplicator.log)

### Additional data
Please don't forget to attach `Deduplicator.log` file present in your Documents folder(present since 1.0.0.100007).
Please note: `Deduplicator.log` could contain some information related to your system including but not limited to:

 * OS version W10
 * OS architecture x64
 * CPU cores amount 16 (2 sockets Xeon X5687)
 * RAM size 24GB
 * Display details such as resolution 30inch NEC (2560*1600) + 19 inch NEC (1200*1600)
 * Filesystem paths to images processed by Deduplicator
N:\Pictures\Photos
You could always check `Deduplicator.log` file and mask all the data you think is sensible or private.

**Please check `Deduplicator.log` each time you're creating an issue!**

**Comment by teran** [comment]
Hello @Delmouly,

First of all thanks for reporting the issue!

I've just reproduced installation procedure on macOS with the latest Lightroom Classic CC as following steps:

- Download zip archive with the plugin
- Open Lightroom Classic CC
- Go to `File` -> `Plug-in Manager ...`
- Press `Add` button and choose the unpacked plugin

I've also verified menu items:
- `Library` -> `Plug-in Extras` -> `Deduplicator` -> `Find duplicates`
- `Help` -> `Plug-in Extras` -> `Deduplicator` -> `Check for updates`

And everything works perfect and as expected: Plug-in manager indicates the plugin is installed and running, menu items on their places.

So let's try the check out what is wrong in your setup:

- Please ensure you the latest Lightroom Classic version available for your platform. If you have Lightroom Classic CC you could easily check it via Adobe Cloud utility. Please note, the plugin _should_ work correctly on Lightroom 6 and higher because of API compatibility, but proper testing was performed on the latest Lightroom Classic CC. 
- Please post your version of Lightroom (if you have the old one)/Lightroom Classic CC
- Please post screenshot of the `Plug-in Manager` window right after plugin installation
- I see from your description you tried to find the plugin at `File` -> `Plug-in Extras` but it places the main control to `Library` -> `Plug-in Extras`, please check if it's present.

And to ensure your bundle is not corrupted during downloading here's SHA256 checksum for the latest Deduplicator plugin v1.0.2.100010:
```
61de0c5b201b8d65428c53e4d0a3172156ef1d05cf2a7efabd3c6a1fe1523bf8  deduplicator.lrplugin.zip
```

Hope this helps and waiting for further details.

**Comment by Delmouly** [comment]
Hi Igor
Thanks for the quick answer. 
I'm not at home right now but reading your message below I guess my problem is simple : I wasnt looking at the right menu !
I didnt even know there was à "Library/plugin extra" menu.....
Thanks again 

Grégoire

**Comment by teran** [comment]
@Delmouly ok, Please let me know on results checking that :)

**Comment by Delmouly** [comment]
It works as it should, looking in the appropriate menu ! Shame on me. Like my father always said : when everything fails, read the instructions !!
Thanks 
By the way : is there a way to define what duplicates actually are for the plugin (like Teekesselchen)? Or is it just straightforward one way ? 

Grégoire Smith

**Comment by teran** [comment]
@Delmouly glad to hear it works for you :)

> By the way : is there a way to define what duplicates actually are for the plugin (like Teekesselchen)? Or is it just straightforward one way ?

Yes! it will work on selection if you select more than one photo. No matter if it's from collections, folders, whatever else, the only requirement: you need to have files available locally.

**Comment by Delmouly** [comment]
Thanks. 
By "defining what duplicates actually are" I meant the way the plugin understands what a duplicate is or not. Can the same image in Jpeg and raw be seen as a duplicate or not, or the same image in 2 or more différent sizes, or with different file names, or file size etc. 
Thanks again 

Grégoire Smith

**Comment by teran** [comment]
@Delmouly oh, got it.

I've checked out Teekesselchen btw, so let me explain the difference on how deduplicator and Teekesselchen are working first. Teekesselchen uses file metadata stored in the format called EXIF which could be used for plain comparison on other files, i.e. if you have two photos made exactly at the same time and let's say at the same place - mostly like they're duplicates.

deduplicator uses [imgsum](https://github.com/teran/imgsum) - the utility to calculate perceptual hash right from the image(not a file, but image itself), the algorithm it uses have some precision which could work good or bad, depending on what image contains of. For example if you have 5 photos made in completely dark environment and almost black most likely they will be treated as duplicates because they have mostly the same perception. This approach obviously have some pros and cons such as precision.

Now [imgsum](https://github.com/teran/imgsum) [uses average hashing](https://github.com/teran/imgsum/blob/master/image/image.go#L117) function from the image squared to 1024x1024 which looks as the most universal option for me(but that's not sure ;) so I've not implemented the option to tune it any way: choose hash function and/or image resolution to hash.

At the same time I thought to start using thumbnails for image hashing instead of original files, which would improve performance and allow to use deduplicator file master files are offline.

So I've [created a task](https://github.com/teran/imgsum/issues/2) for a way to tune options on imgsum such as pass them from the Plug-in.

Thanks for idea!

**Comment by Delmouly** [comment]
Hi Igor thanks a lot for your great support !
Deduplicator is the much more "intelligent" than teekesselchen;-)
One great option would be to organise the found duplicates. 
for example if dd finds 4 copies of one same image, let's say in 3 différent sizes, and 2 different formats (Jpeg and RAW), it would be great to automaticly choose the larger sized one, in RAW format. This chosen image could be flagged , red color or whatever. 
The aim here is to accelerate the elimination of the unwanted duplicates in large catalogs with thousands of duplicates. Going though every duplicates sets and choosing which one to keep and which one to dump can be a daunting task...
Thanks again 

Grégoire Smith

**Comment by teran** [comment]
@Delmouly Hello and thank for so kind words :)

> One great option would be to organise the found duplicates.

I thought about that right from the start and wanted to stack suspected duplicates in the collection but there was no API handler for that.

Your proposal looks good in addition to stacking because otherwise it will make a false positive feeling you can just select all without flag/red label/etc. and just remove it which is wrong because image hashing has it's own precision.

But anyway I'll check out the latest Lightroom SDK release, probably there would be something could help here.

Thanks! :)

**Comment by teran** [comment]
Looks like the issue is resolved :)
