### ISSUE TITLE
Error while executing imgsum on MacOS

### ISSUE THREAD

**Issue by EdenEitani** [teran/deduplicator#6]
### What you've done step-by-step
Installed the plugin, then went to Library->Plugin Extras -> find duplicates

### What you've expected to get as a result

<img width="427" alt="Screen Shot 2021-11-13 at 12 46 49" src="https://user-images.githubusercontent.com/16803684/141615638-9af9e207-e14f-4ec1-bf7c-ae46bfc76835.png">

### Additional data
[Deduplicator.log](https://github.com/teran/deduplicator/files/7531857/Deduplicator.log)

 * OS version - Mac OS catalina 10.15.7
 * RAM size - 16 GB

**Comment by teran** [comment]
Hello @EdenEitani,

Thank you for your feedback!
Looking at the log file you have provided I see there's a folder in path named in non-ASCII. Normally that should not make any problems since macOS utilises unicode for them but could you please try renaming that folder to ASCII character set just to check if that's related?

Thanks.

**Comment by EdenEitani** [comment]
I tried to rename it and also tried to put it in a collection but I get the same error
[Deduplicator.log](https://github.com/teran/deduplicator/files/7531915/Deduplicator.log)

**Comment by teran** [comment]
Hello @EdenEitani,

I just tried to reproduce the issue with non-ASCII directory and it worked find, so I suppose it could be the issue related to how Lightrooms runs the imgsum binary file.

Could you please confirm it's the only error from Lightroom and you're not receiving any other notifications related unsigned binary?
Please also check if there's a "Allow anyway" button for imgsum-amd64 at System preferences -> Security & Privacy -> General tab? If so - allowing to run the imgsum-amd64 should fix the issue.

PS. Just to make you informed what happened - I suppose macOS Catalina blocks `imgsum-amd64` binary which is vendored with Deduplicated to run because it's unsigned i.e. not cryptographically signed by identified (by Apple) developer. In some cases unsigned binaries could contain malicious code so your decision to allow it to run should be informed. So imgsum - is an application written in Go and published under GPLv2 terms here: https://github.com/teran/imgsum you're free to check out source code and scan Deduplicator distribution at virustotal.com or your own antivirus to ensure it's totally safe. Please also note I just tried to use virustotal.com for scanning Deduplicator distribution and it shows one scanner of 57 available marked it as malicious because of hashing algorithms used within, I notified all of antivirus software vendors a couple of years ago but it looks like not all of them fixed that.

**Comment by EdenEitani** [comment]
It seems like I don't even have imgsum-amd64 on the plugin directory 
where should I download it from?

**Comment by teran** [comment]
@EdenEitani,

You normally shoundn't since it's vendored with release.
If you don't have it that could mean the case I've described since macOS provides you an option to remove the binary right when choosing if it's allowed to run.

So please check the preference pane at System preferences -> Security & Privacy -> General tab and reinstall the plugin to get imgsum-amd64 back. Here's the latest release https://github.com/teran/deduplicator/releases/tag/1.0.3.20191210033724

**Comment by EdenEitani** [comment]
Yes, that was the problem (Not the security but I downloaded devlrplugin and not the latest release.

Can you please attach the download link on the front readme page? its not there :)

Have a good day!

**Comment by teran** [comment]
@EdenEitani sure, already done!

Thank you four your feedback and using Deduplicator plugin :)
